name: Tom CI

on:
  push:
    branches: 
      - '*'
  pull_request:
    branches: 
      - '*'

jobs:
  build:

    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Bundle Install
      run: bundle install
    - name: Build and test
      run: bundle exec fastlane scan --destination "${destination}" --scheme "Tom-Example"
